### ISSUE TITLE
Issue in Exercise 2.2.

### ISSUE THREAD

**Issue by vikramsinghanttal** [iamhectorotero/rlai-exercises#11]
Hey Hector,
I think there is a mistake in exercise 2.2. I referred to Barto and Sutton 2nd edition.

**Exercise 2.2** : _Bandit example_ Consider a k-armed bandit problem with k = 4 actions, denoted 1, 2, 3, and 4. Consider applying to this problem a bandit algorithm using ε-greedy action selectioni, sample average action-value estimates, and initial estimates of Q1(a) = 0, for all a. Suppose the initial sequence of actions and rewards is A1 = 1, R1 = -1,  A2 = 2, R2 = 1,  A3 = 2, R3 = -2,  A4 = 2, R4 = 2,  A5 = 3, R5 = 0. On some of these time steps the ε case may have occurred, causing an action to be selected at random. On which time steps did this definitely occur? On which time steps could this possibly have occurred.

## Answer:
Estimates @ step 1: (1, 0) (2, 0) (3, 0) (4, 0)
The action selected is _1_. We don't have any information of how ties are broken, so it could have been selected **either randomly or greedily** using the tie-breaking strategy. Action  _1_  received a reward of -1 making the sample average action value estimate = -1.

Estimates @ step 2: (1, -1) (2, 0) (3, 0) (4, 0)
The action selected is _2_. We don't have any information of how ties are broken, so it could have been selected **either randomly or greedily** using the tie-breaking strategy. Action  _2_  received a reward of 1 making the sample average action value estimate = 1.

Estimates @ step 3: (1, -1) (2, 1) (3, 0) (4, 0)
The action selected is _2_.  Action  _2_ is likely to be **selected greedily** _2_  as it has the highest reward, or could be an **ε case**. Action  _2_  received a reward of -2 making the sample average action value estimate = -1/2.

Estimates @ step 4: (1, -1) (2, -1/2) (3, 0) (4, 0)
The action selected is _2_ which has lower average action value estimate than 3 and 4.  Hence its surely a **random selection**, an ε case.  Action  _2_  received a reward of 2 making the sample average action value estimate = 1/3.

Estimates @ step 5: (1, -1) (2, 1/3) (3, 0) (4, 0)
The action selected is _3_ which is a definite **random selection**, an ε case, since the greedy action is _2_.

To sum up, the cases where the ε case (random selection) definitely occurred are steps 4 and 5.
The rest of the cases could be a consequence of a greedy selection or a coincidence with a random choice.

## Answer:
Estimates @ step 1: (1, 0) (2, 0) (3, 0) (4, 0)
The action selected is _1_. We don't have any information of how ties are broken, so it could have been selected
either randomly or greedily using the tie-breaking strategy.

Estimates @ step 2: (1, 1) (2, 0) (3, 0) (4, 0)
The action selected is _2_. This is a **random** selection as the greedy selection would have been choosing action _1_.

Estimates @ step 3: (1, 1) (2, 1) (3, 0) (4, 0)
The action selected is _2_. Both actions _1_ and _2_ could be the greedy selection, or an ε case.

Estimates @ step 4: (1, 1) (2, 3/2) (3, 0) (4, 0)
The action selected is _2_ which is the greedy choice as well.

Estimates @ step 5: (1, 1) (2, 5/3) (3, 0) (4, 0)
The action selected is _3_ which is a definite ε case, since the greedy action is _2_.

To sum up, the cases where the ε case definitely occurred are steps 2 and 5.
The rest of the cases could be a consequence of a greedy selection or a coincidence with a random choice.

## Request
Please review my solution.

Thanks
Vikram

**Comment by iamhectorotero** [comment]
Yes, your solution is correct @vikramsinghanttal! In fact, I have just accepted a pull request (#9) with similar contents. 

When I did these exercises the problem statement had a different reward sequence (and thus the solution was different too). The statement was after corrected in the [errata](http://incompleteideas.net/book/errata.html).
